Cargo.toml, src/errors.rs, src/lib.rs, src/utils.rs
Use `config_dir` instead of getting "HOME" and then attaching the ".config" dir.
This way it will theoretically work on MacOS and Windows as well.
Made the functions more generic.
Added "dirs" and "thiserror" for directory handling and error handling
Created a custom error type and added error handling
Added proper error handling here. `unwrap` and `expect` can still be used wherever we use this library but we will have a better overview of what is happening when creating tests etc.
On making functions more generic:
It makes sense to take `impl Into<String>`, `impl AsRef<str>` etc. as it makes it possible to call the functions with either a `String` or a `&str`.
If a function becomes a lot larger we can write wrappers around them if we want to cut down on the amount of code generated, …
=> added some error handling and use of `dirs::config_dir`

Cargo.toml, ic-storage/Cargo.toml, ic-storage/ic-storage-derive/Cargo.toml, ic-storage/ic-storage-derive/src/lib.rs, ic-storage/src/lib.rs, ic-storage/tests/derive.rs, src/storage.rs
This PR adds a derive macro for `IcStorage` trait, that provides a safe and simple way to use canister local storage.
=> [CPROD-353] Adds ic-storage crate

canisters/src/factory/api.rs, canisters/src/factory/core.rs, canisters/src/factory/state.rs, canisters/src/is20/principal_ext.rs, canisters/src/pair/types.rs
* Remove `State` struct completely from this crate. Instead, it expects the macro users to provide `State` that implements `IcStorage`. This is done to remove usage of unsafe `static mut` and make it more flexible for the crate consumers.
* Instead of `init_state` macro `impl_factory_state_management` is added. It provides convenient way to implement stable storage functions for the state object. It does not include `#init` method though, so it should be implemented by hand.
* Removes notion of `admin` and all the methods, related to it. Not all consumers of the factory helpers require admin checks. Also, upgrade method, the only method that used `admin` value inside ic_helpers, does not really need the admin check. Instead, we should probably add cycles check and consuming in the upgrade …
=> [CPROD-370] Refactoring of factory state management

ic-helpers/src/factory/core.rs
Necessary for https://github.com/infinity-swap/IS20/pull/32
=> fix: don't force the wasm_module for upgrades to be `&'static`

ic-helpers/Cargo.toml, ic-helpers/src/factory/api.rs
Problem: When building canisters from `ic-canister::Canister` trait
we have no api to generate factory endpoints to it.
Solution: Add `extend-with-factory-api` macro that takes the
existing canister and extends it with the api needed.
=> [WPROD-53] Add `extend-with-factory-api` macro

ic-canister/ic-canister-macros/Cargo.toml, ic-canister/ic-canister-macros/src/derive.rs, ic-canister/tests/canister_a/Cargo.toml, ic-canister/tests/canister_b/Cargo.toml
This had names clashing if you create token canisters like in the example below
```rust
mod Token0 {
#[derive(Clone, Canister)]
pub struct Token0Canister {
#[id]
principal: Principal,
}
}
mod Token1 {
#[derive(Clone, Canister)]
pub struct Token1Canister {
#[id]
principal: Principal,
}
}
```
=> [WPROD-53] Add random principal ids for the Canister generated structs

ic-canister/ic-canister-macros/src/canister_call.rs, ic-canister/ic-canister-macros/src/derive.rs, ic-helpers/Cargo.toml, ic-helpers/src/factory/state.rs, ic-helpers/src/ledger/principal_ext.rs
Update ic fork dependency to a more recent branch, to make it possible to use with IC. This also required a little refactoring (renaming `TRANSACTION_FEE` to `DEFAULT_TRANSFER_FEE`.
Also added better error messages for derive macro and added possibility to retrieve canister principal id from inside the canister with simple `self.principal()` call.
=> [CPROD-753] Update ic dependency, refactoring

ic-canister/ic-canister-macros/src/canister_call.rs, ic-canister/ic-canister-macros/src/lib.rs, ic-canister/ic-canister/src/lib.rs, ic-canister/tests/canister_b/src/lib.rs, ic-helpers/src/management/canister.rs
The DFX 0.9.3 uses the older version of the structures for the ECDSA signing code, then defined in dependencies of `ic-helpers`.
In this PR that structures is defined to be compatible with this DFX version.
=> [NPROD-17] Fix ECDSA signing for the new ic dependencies version

ic-canister/ic-canister-macros/src/api.rs, ic-canister/ic-canister-macros/src/canister_call.rs, ic-canister/tests/canister_a/src/lib.rs, ic-canister/tests/canister_b/Cargo.toml, ic-canister/tests/canister_b/src/lib.rs
It turns out that changing the text context ids on simple calls produces some undesirable side effects. For example, when a canister calls its own methods, with such approach the caller id and current canister id get messed up, which breaks many tests.
Instead, we rely on the test author to provide the test context when calling the canister methods directly, and make the `canister_call!` macros substitute the context. This approach is more transparent and less error prone.
=> Fixes tests context ids

ic-canister/ic-canister-macros/src/api.rs, ic-canister/ic-canister-macros/src/derive.rs, ic-canister/ic-canister-macros/src/lib.rs, ic-canister/tests/canister_a/src/lib.rs, ic-canister/tests/canister_b/src/lib.rs, ic-factory/src/api.rs
This commit fixes two issues:
1. The upgrade method in the factory API used `FactoryCanister::get_canister_bytecode` method. When such method is accessed from the FactoryExport struct (the one that is created just for trait APIs), which doesn't and cannot provide an implementation for this method. Instead, we remove this API method from the trait, leaving the actual method logic in the trait. This way, the factory structure implementing the `FactoryCanister` trait can have a one-line API method implementation that just calls the method in the trait providing the wasm code as an argument.
2. The `pre_upgrade` and `post_upgrade` macros reuse the code for other types of API methods, which included requesting the method call arguments from IC. Such a call resulted in a runtime error in a …
=> [CPROD-899] Fix factory upgrade method

ic-helpers/src/tokens.rs
This should allow us to use `nat` in our `.did` files and we can still use `Tokens128` internally
=> Tokens128 ser deser candid

ic-factory/Cargo.toml, ic-factory/src/api.rs, ic-factory/src/core.rs, ic-factory/src/error.rs, ic-factory/src/lib.rs, ic-factory/src/state.rs, ic-factory/src/state/v1.rs, ic-factory/src/types/checksum.rs, ic-factory/src/update_lock.rs, ic-helpers/Cargo.toml, ic-helpers/src/candid_header.rs
* Adds update_lock on the state to prevent state modification while
upgrade or create processes are on the way
* Adds the state check on the canisters before their code is upgraded.
This state check verifies that the state is not modified or if it is,
that it uses a new version as defined by the `Versioned` trait.
* Adds the static typed check on factory operation permissions.
=> [CPROD-964] Refactor the canister factories and add upgrade state check

ic-canister/ic-canister-macros/src/api.rs
This ticket gets rid of `mint` and `burn` features when `no_api` feature is used. We can not run the AMM pair with `no_api` feature as this will also get rid of the `mint` and `burn` methods
=> [CPROD-1165] do not add methods to IDL if no_api feature is used

ic-auction/Cargo.toml, ic-auction/src/error.rs, ic-canister/ic-canister-macros/src/api.rs, ic-factory/Cargo.toml, ic-factory/src/api.rs, ic-factory/src/error.rs, ic-helpers/Cargo.toml, ic-helpers/src/ledger/mod.rs, ic-helpers/src/management/canister.rs, ic-helpers/src/pair/mod.rs, ic-stable-storage/Cargo.toml
Currently there is a bug when trying to deploy v1-amm:
```
Error: The Replica returned an error: code 5, message: "Wasm module of canister rrkah-fqaaa-aaaaa-aaaaq-cai is not valid: Wasm module has an invalid import section. Module imports function '__wbindgen_describe' from '__wbindgen_placeholder__' that is not exported by the runtime."
``` 
That is because ic devs have inconsistent versioning in their codebase. We've decided to upgrade the ic dependencies to be able to use their canisters further.
=> [CPROD-1163] Update IC dependency

ic-auction/Cargo.toml, ic-auction/src/api.rs
These outputes are very enoying especially in integration tests, but can be usefull for debugging. So I added a `debug` feature to add them when needed.
=> Remove debug outputs for auction by default

ic-stable-structures/src/storage_wasm/structures_wasm.rs
Methods `len()` and `is_empty()` added to wasm wrappers for `StableBTreeMap`.
=> [EPROD-60] len() and is_empty() for wasm StableBTreeMap

ic-factory/Cargo.toml, ic-factory/src/api.rs, ic-factory/src/state.rs, ic-stable-structures/src/storage/structures/unbounded.rs
`ic-factory` stores it's state in the stable storage now.
=> [CPROD-1423] Factory stable storage

.github/workflows/build_and_tests.yml, Cargo.toml, dfx.json, ic-payments/build_payments_canister.sh, ic-payments/state_machine_test.sh, ic-stable-structures/Cargo.toml, ic-stable-structures/src/error.rs, ic-stable-structures/src/storage/structures/vec.rs, ic-stable-structures/src/storage_wasm/structures_wasm.rs, ic-stable-structures/tests/did/Cargo.toml, ic-stable-structures/tests/did/src/lib.rs, ic-stable-structures/tests/dummy_canister/.gitignore, ic-stable-structures/tests/dummy_canister/Cargo.toml, ic-stable-structures/tests/dummy_canister/dummy_canister.did, ic-stable-structures/tests/dummy_canister/src/canister.rs, ic-stable-structures/tests/dummy_canister/src/canister/service.rs, ic-stable-structures/tests/dummy_canister/src/main.rs, ic-stable-structures/tests/integration_test.rs, ic-stable-structures/tests/state_machine/btreemap.rs, ic-stable-structures/tests/state_machine/cell.rs, ic-stable-structures/tests/state_machine/log.rs, ic-stable-structures/tests/state_machine/map.rs, ic-stable-structures/tests/state_machine/mod.rs, ic-stable-structures/tests/state_machine/multimap.rs, ic-stable-structures/tests/state_machine/vec.rs, ic-stable-structures/tests/utils/mod.rs, ic-stable-structures/tests/utils/wasm.rs, scripts/build.sh, scripts/build_dummy_canister.sh
Run integration test for stable-structures with
```sh
export WASMS_DIR="../target/wasm32-unknown-unknown/release/"
dfx build dummy_canister && cargo test -p ic-stable-structures@0.3.53 --features state-machine
```
=> EPROD 381 Stable structs get corrupted after upgrade

Cargo.toml, ic-canister/ic-canister-macros/src/canister_call.rs
To call the vitual_canister_call macro from other utility functions, the method name and arguments type was changed to generic expressions.
=> EPROD-421 used generic expressions in virtual_canister_call

ic-stable-structures/src/memory_mapped_files/memory.rs, ic-stable-structures/src/memory_mapped_files/memory_mapped_file.rs, ic-stable-structures/tests/memory_mapped_files/mod.rs
Before we were reserving 1 TB of virtual memory space for each memory-mapped file. Which is OK for a single x64 application which has 2^48/2 = 128 TB user address space. But if we are running EVMC tests concurrently where several dozens of files are created for each state we may end up getting memory allocation error (which is actually address space allocation error).
That's why I've added a possibility to change the default reserved length, now it is used in tests only.
=> Add reserved length setting

Cargo.toml, ic-crypto-getrandom-for-wasm/Cargo.toml, ic-crypto-getrandom-for-wasm/src/lib.rs
The `ic-crypto-getrandom-for-wasm` package, which is a workaround for the `getrandom` dependency issues in WASM environments, doesn't work in all cases. Sometimes, just including the package in `Cargo.toml` isn't enough.
This PR provides a fix that changes how this package is consumed...
To register this new custom implementation, call the function inside of your canister's `init` method or wherever canister initialization happens, with conditional compilation, like this:
```rust
#[init]
pub fn init(&mut self) {
#[cfg(target_family = "wasm")]
ic_crypto_getrandom_for_wasm::register_custom_getrandom();
}
```
=> Fix: `getrandom` dependency issue in WASM build

ic-task-scheduler/src/retry.rs
In some cases we want to retry the operation with some interval until some fixed moment in the future. For example, we want to wait for a transaction in BTC network to be taken from the mempool and mined into a block, and we want to wait for a set time (most mempools will drop transaction from the mempool in 24 or 72 hours).
=> Add timeout retry policy to the scheduler

ic-task-scheduler/src/error.rs, ic-task-scheduler/src/scheduler.rs
Currently there are two ways for a scheduler task to fail:
1. Return a `SchedulerError::TaskExecutionFailed` error to make the schduler retry the task execution according to the retry policy. When the maxim retries number is achieved, the task is marked as failed.
2. Panic inside the task to revert any state changes and make the scheduler kill the task by timeout.
In some cases we need the task to fail without retries, but to preserve the state update by the task. For example, if the input data given to the task is incorrect, we want to set operation state as failed and complete, as this operation cannot be retried in the future with the same input data, and we don't want to retry the operation according to the retry policy.
For such cases, I add an `Unrecoverable` error type for the …
=> Add unrecoverable scheduler error

ic-task-scheduler/src/scheduler.rs
Currently the timeout message is printed every time a scheduler meets a running task, because the message is printed before the timeout check.
=> Fix printing a warning on non-timeedout tasks

Cargo.toml, ic-log/Cargo.toml, ic-log/examples/log_canister.rs, ic-log/src/canister.rs, ic-log/src/canister/inspect.rs, ic-log/src/canister/state.rs, ic-log/src/did.rs, ic-log/src/lib.rs, ic-log/src/settings.rs, ic-log/src/writer.rs, ic-log/tests/in_memory_logger.rs, ic-stable-structures/src/structure/stable_storage/cell.rs, scripts/build.sh
This PR add canister trait with the following features:
* logger access ACL checks
* logger configuration
The trait itself is hidden behind the `canister` feature, so any canister that wants to use the logger without importing all the API stuff can still do so.
Updates to the logger logic itself:
* `in_memory_records` settings is now not an option. If set to 0, in-memory logging will be disabled (same behavior as `None` value had before). This allows us to make this value configurable on-line.
* added `max_entry_length` setting to limit the possibility of DOS attacks by creating some very log logs
=> Add common logger canister trait

ic-log/src/canister/state.rs
Found another bug in the log canister implementation.
=> Fix ACL restoration after reload

Cargo.toml, ic-task-scheduler/src/scheduler.rs
This change is required to implement https://infinityswap.atlassian.net/browse/EPROD-961 . Change is backward compatible, so I update the patch number only.
=> Add `find_id` and `reschedule` methods to scheduler

Cargo.toml, ic-canister/ic-canister-macros/Cargo.toml, ic-canister/ic-canister-macros/src/export_candid.rs, ic-canister/ic-canister-macros/src/lib.rs, ic-canister/ic-canister-macros/tests/export_candid.rs, ic-canister/ic-canister-macros/tests/export_candid/expended/empty_attr_arguments.rs, ic-canister/ic-canister-macros/tests/export_candid/expended/valid_return_type.rs, ic-canister/ic-canister-macros/tests/export_candid/not_expended/invalid_attr_arguments.rs, ic-canister/ic-canister-macros/tests/export_candid/not_expended/invalid_attr_arguments.stderr, ic-canister/ic-canister-macros/tests/export_candid/not_expended/invalid_item_type.rs, ic-canister/ic-canister-macros/tests/export_candid/not_expended/invalid_item_type.stderr, ic-canister/ic-canister-macros/tests/export_candid/not_expended/invalid_return_type.rs, ic-canister/ic-canister-macros/tests/export_candid/not_expended/invalid_return_type.stderr, ic-canister/ic-canister-macros/tests/export_candid/not_expended/no_return_type.rs, ic-canister/ic-canister-macros/tests/export_candid/not_expended/no_return_type.stderr, ic-canister/ic-canister/Cargo.toml, ic-canister/ic-canister/src/lib.rs
Adds an attribute macro to make our canisters usable by the `candid-exporter` tool.
Closes https://infinityswap.atlassian.net/browse/EPROD-995
=> feature: Add `export_candid` attribute macro

ic-auction/src/state.rs, ic-canister/ic-canister-macros/src/api.rs, ic-log/src/formatter/humantime.rs, ic-log/src/formatter/mod.rs, ic-stable-structures/src/structure/stable_storage/multimap.rs
This commit removes checks by the `query`, `update` and `init` macroses that there are duplicate methods with the same name.
The reason this causes an issue is that in contrast with the rustc, rust-analyzer expands macroses using the same process all the time. This means that lazy_static storage for the macro is not dropped between invocations which produces the error. After this change, the new declaration of the method expanded by the rust-analyzer will just replace the old one.
This will change will also make the macros' implementation more correct for 2 reasons:
1. The checks we had are not reliable. They only check for duplication inside one crate, which in most cases is already coverred by the compiler when it check that there are no 2 methods with the same name.
2. Even if there …
=> Fix errors when using rust-analyzer with canister method attributes

ic-canister-client/src/pocket_ic.rs
Added live mode flag to be able to use the update methods for live mode instead of default
=> EPROD-1156-live mode on pocket ic client
